### ISSUE TITLE
Question/Comment about the BikeStopState.cs and BikeTurnState.cs

### ISSUE THREAD

**Issue by fscopel** [PacktPublishing/Game-Development-Patterns-with-Unity-2021-Second-Edition#1]
I noticed the `private BikeController _bikeController` in both of those classes goes unused. It small but there is the check and assignment of the `_bikeController` on every call to the `Handle` function, just feels a little wasteful.  Is it there just in case later on something needs to happen outside the `Handle` ?

**Comment by dbaron-gamedev** [comment]
Thank you for your feedback. 

I don't seem to see which classes you are referring to in your comment but I imagine it's in a state class. 

Yes, the context you are describing, this approach could be wasteful in certain cases.

In the book, I presented a simplified use of the pattern with minimum optimization but yes, avoiding an assignment of _bikeController on every call of the Handle function is a potential optimization to do.

**Comment by fscopel** [comment]
Your reply is much appreciated. Thank you.
